name: Keep Backend Warm

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes UTC
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render root (with retries)
        run: |
          set -e
          URL="https://mindmapper-crll.onrender.com/"
          # Try up to 4 times with small delays to survive cold starts
          curl --silent --fail --location \
               --retry 4 --retry-delay 5 --max-time 25 \
               "$URL" >/dev/null
          echo "✅ Warmed: $URL"