name: Keep Backend Warm

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes UTC
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl --silent --fail https://mindmapper-crll.onrender.com/ping >/dev/null